apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kingshot-role-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Alby02/kingshot-role-manager.git
    targetRevision: HEAD
    path: helm/kingshot-role-manager
    helm:
      values: |
        config:
          database:
            host: shared-postgres-rw.pg-clusters.svc.cluster.local
            port: "5432"
            name: kingshot-role-manager
            user: kingshot
        secret:
          create: false
          existingSecret: krm-credentials
  destination:
    server: https://kubernetes.default.svc
    namespace: kingshot-role-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true